experiment:
  runs: 4

problem:
  name: tsp
  params:
    distance_matrix:
      - [0, 29, 20, 21, 16, 31, 100, 12, 4, 31]
      - [29, 0, 15, 29, 28, 40, 72, 21, 29, 41]
      - [20, 15, 0, 15, 14, 25, 81, 9, 23, 27]
      - [21, 29, 15, 0, 4, 12, 92, 12, 25, 13]
      - [16, 28, 14, 4, 0, 16, 94, 9, 20, 16]
      - [31, 40, 25, 12, 16, 0, 95, 24, 36, 12]
      - [100, 72, 81, 92, 94, 95, 0, 90, 101, 99]
      - [12, 21, 9, 12, 9, 24, 90, 0, 15, 25]
      - [4, 29, 23, 25, 20, 36, 101, 15, 0, 35]
      - [31, 41, 27, 13, 16, 12, 99, 25, 35, 0]
    start_city: 0

algorithms:
  # Classical algorithms
  BFS:
    timeout: 60
  UCS:
    timeout: 60
  Greedy:
    timeout: 60
  AStar:
    timeout: 60
  # Metaheuristic algorithms
  GA_TSP:
    timeout: 60
    max_iters: 500
    pop_size: 50
    mutation_rate: 0.2
    crossover_rate: 0.9
  HillClimbingTSP:
    timeout: 60
    max_iters: 1000
    n_neighbors: 50
    two_opt: true
  SimulatedAnnealingTSP:
    timeout: 60
    max_iters: 5000
    initial_temp: 1000
    cooling_rate: 0.995
    two_opt: true
